name: CI
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - Readme.md

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup docker build
        uses: docker/setup-buildx-action@v1

      - name: Login do DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/game:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Update tag
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/mywebsite-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "chandaneyash10@gmail.com"
          git config --global user.name "yashchandane123"
          git add helm/mywebsite-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
