name: CI
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - Readme.md
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/game:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper analysis
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  owasp-dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET 6.0 Runtime
        run: |
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0 || sudo apt-get install -y dotnet-runtime-6.0

      - name: Download and Extract OWASP Dependency-Check
        run: |
          curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip -o dependency-check-8.4.0-release.zip -d dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          chmod +x dependency-check/bin/dependency-check.sh
          dependency-check/bin/dependency-check.sh --scan . --format "HTML" --out reports

      - name: Upload OWASP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Dependency-Check-Report
          path: reports/

  trivy-security-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: owasp-dependency-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSL https://github.com/anchore/syft/releases/download/v0.56.0/syft_0.56.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin syft

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Generate SBOM using Syft
        run: syft . -o cyclonedx-xml > sbom.xml

      - name: Run Trivy FS Scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL --format table . > trivy-fs-results.txt

      - name: Run Trivy Image Scan
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL --format table -o trivy-image-results.txt ${{ secrets.DOCKERHUB_USERNAME }}/game:${{ github.run_id }} || true

      - name: Upload Trivy FS Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-results
          path: trivy-fs-results.txt

      - name: Upload Trivy Image Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-results
          path: trivy-image-results.txt

      - name: Upload Trivy SBOM Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-results
          path: sbom.xml

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: trivy-security-scan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "chandaneyash10@gmail.com"
          git config --global user.name "yashchandane123"

      - name: Pull Latest Changes and Auto-Resolve Conflicts
        run: |
          git fetch origin main
          git checkout main
          git pull origin main --rebase --autostash || (git rebase --abort && git pull --no-rebase)
          git merge --strategy-option=ours origin/main

      - name: Update Helm Chart Tag
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/game-chart/values.yaml

      - name: Commit and Push Changes
        run: |
          git add helm/game-chart/values.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update tag in Helm chart"
            git push origin main || echo "Push failed. You might need to resolve conflicts manually."
          fi
