name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/game:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

  pull-latest-image:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Pull Latest Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/game:${{ github.run_id }}

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate Status
        run: |
          STATUS=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
          if [[ "$STATUS" == "FAILED" ]]; then
            echo "SonarCloud Quality Gate Failed!"
            exit 1
          fi

  owasp-dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        run: |
          curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip -o dependency-check-8.4.0-release.zip -d dependency-check
          mv dependency-check/dependency-check/* dependency-check/
          chmod +x dependency-check/bin/dependency-check.sh
          dependency-check/bin/dependency-check.sh --scan . --format "HTML" --out reports || exit 1

      - name: Upload OWASP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Dependency-Check-Report
          path: reports/

  trivy-security-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: owasp-dependency-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Trivy Image Scan
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL --format table -o trivy-image-results.txt ${{ secrets.DOCKERHUB_USERNAME }}/game:${{ github.run_id }} || true

      - name: Upload Trivy Image Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-results
          path: trivy-image-results.txt

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: [push, trivy-security-scan]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "chandaneyash10@gmail.com"
          git config --global user.name "yashchandane123"

      - name: Update Helm Chart Tag
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/game-chart/values.yaml

      - name: Commit and Push Changes
        run: |
          git add helm/game-chart/values.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update tag in Helm chart"
            git push origin main || echo "Push failed. You might need to resolve conflicts manually."
          fi
